RUN_PARTS:
  SEGMENTATION: True
  INSTANCES: True
  MATCHING: True
SAVE_NAMES:
  SEGMENTATION: "segmentation.npy"
  INSTANCES: "instances.npy"
  MATCHING: "matching.npy"
LOAD_NAMES:
  SEGMENTATION: "segmentation.npy"
  INSTANCES: "instances.npy"
  MATCHING: "matching.npy"
DATA_PATH: "common/data/split_sample.npz"
CUDA_CARD: 'cuda:0'
XML_FILE_NAME: "result.xml"
ANIMATION: False

MODEL_CONFIG_PATH: "common/pipeline/models/model01/pandar.yaml"
MODEL_PARTITION_SIZE: 35
MODEL_VOXEL_SIZE: 0.15
MODEL_SAVE_DEBUG: False
MODEL_RETURN_UPSAMPLED: True
MODEL_SELECTION_STRATEGY: "last"
MODEL_MAX_NUM_PTS: 1000000
MAX_DISTANCE: 16
MIN_Z_HEIGHT: -5


POSTPROCESSING_INTENSITY_TRESH: 105