RUN_PARTS:
  SEGMENTATION: True
  INSTANCES: True
  MATCHING: True
SAVE_NAMES:
  SEGMENTATION: "segmentation.npz"
  INSTANCES: "instances.npz"
  MATCHING: "matching.npz"
LOAD_NAMES:
  SEGMENTATION: "segmentation.npz"
  INSTANCES: "instances.npz"
  MATCHING: "matching.npz"
DATA_PATH: "common/data/LR1_local-001.pcd"
