RUN_PARTS:
  SEGMENTATION: False
  INSTANCES: False
  MATCHING: True
SAVE_NAMES:
  SEGMENTATION: "segmentation.npy"
  INSTANCES: "instances.npy"
  MATCHING: "matching.npy"
LOAD_NAMES:
  SEGMENTATION: "segmentation.npy"
  INSTANCES: "instances.npy"
  MATCHING: "matching.npy"
DATA_PATH: "common/data/LR1_local-001.pcd"
CUDA_CARD: 'cuda:3'