RUN_PARTS:
  SEGMENTATION: True
  INSTANCES: True
  MATCHING: True
SAVE_NAMES:
  SEGMENTATION: "segmentation.npy"
  INSTANCES: "instances.npy"
  MATCHING: "matching.npy"
LOAD_NAMES:
  SEGMENTATION: "segmentation.npy"
  INSTANCES: "instances.npy"
  MATCHING: "matching.npy"
DATA_PATH: "common/data/LR1_local.pcd"
CUDA_CARD: 'cuda:0'
XML_FILE_NAME: "result.xml"
ANIMATION: True