RUN_PARTS:
  SEGMENTATION: True
  INSTANCES: True
  MATCHING: True
SAVE_NAMES:
  SEGMENTATION: "segmentation.npy"
  SEGMENTATION_DOWNSAMPLE: "segmentation_downsample.npy"
  INSTANCES: "instances.npy"
  MATCHING: "matching.npy"
LOAD_NAMES:
  SEGMENTATION: "segmentation02.npy"
  INSTANCES: "instances.npy"
  MATCHING: "matching.npy"
DATA_PATH: "/home/koondra/temp_school/lane_marking/frame_id_correction/Lane-extraction/test.npz"
CUDA_CARD: 'cuda:0'
XML_FILE_NAME: "result.xml"
OUTPUT_FILE_NAME: "output.npz"
ANIMATION: True

MODEL_CONFIG_PATH: "common/pipeline/models/model02/model_checkpoint_wd_config.yaml"
MODEL_PARTITION_SIZE: 60 #60 for model 2 / 30 for model 1
MODEL_VOXEL_SIZE: 0.15
MODEL_SAVE_DEBUG: False
MODEL_SELECTION_STRATEGY: "last"
MODEL_MAX_NUM_PTS: 1000000
MAX_DISTANCE: 16
MIN_Z_HEIGHT: -20


POSTPROCESSING_INTENSITY_TRESH: 100