RUN_PARTS:
  SEGMENTATION: True
  INSTANCES: False
  MATCHING: False
SAVE_NAMES:
  SEGMENTATION: "segmentation.npy"
  INSTANCES: "instances.npy"
  MATCHING: "matching.npy"
LOAD_NAMES:
  SEGMENTATION: "segmentation.npy"
  INSTANCES: "instances.npy"
  MATCHING: "matching.npy"
DATA_PATH: "common/data/split_sample.npz"
CUDA_CARD: 'cuda:0'
XML_FILE_NAME: "result.xml"
ANIMATION: False

MODEL_CONFIG_PATH: "/datagrid/personal/vacekpa2/kodejond/complete_training/preproc_test01/model_checkpoint_config.yaml"
MODEL_PARTITION_SIZE: 80
MODEL_VOXEL_SIZE: -1
MODEL_SAVE_DEBUG: False
MODEL_RETURN_UPSAMPLED: False
MODEL_SELECTION_STRATEGY: "last"
MODEL_MAX_NUM_PTS: 3000000
POSTPROCESSING_INTENSITY_TRESH: 105